# Benchmark system configuration
registry_addrs:
  - "http://node1:9000"

fault_tolerance_request_interval_value: 1
# deploy time oracle on node2
time_oracle_url: "http://node2:8010"
zipfian_constant: 0.99
latency_value: 0

# Redis configuration
redis_addr: "node2:6379"
redis_password: "kkkzoz"

# MongoDB configuration
mongodb_addr1: "mongodb://node2:27017"
mongodb_addr2: "mongodb://node3:27018"
mongodb_username: "admin"
mongodb_password: "password"

# KVRocks configuration
kvrocks_addr: "172.24.58.116:6666"
kvrocks_password: "kkkzoz"

# CouchDB configuration
couchdb_addr: "http://localhost:5984"
couchdb_username: "admin"
couchdb_password: "password"

# Other databases configuration
cassandra_addr: ["10.206.206.4"]
dynamodb_addr: "http://localhost:8000"
tikv_addr: ["172.24.58.116:2379"]
