# Benchmark system configuration
registry_addrs:
  - "http://10.206.206.2:9000"
  - "http://10.206.206.6:9000"
  - "http://10.206.206.7:9000"

fault_tolerance_request_interval_value: 1
# deploy time oracle on node2
time_oracle_url: "http://10.206.206.3:8010"
zipfian_constant: 0.99
latency_value: 0

# Redis configuration
redis_addr: "10.206.206.3:6379"
redis_password: "kkkzoz"

# MongoDB configuration
mongodb_addr1: "mongodb://10.206.206.3:27017"
mongodb_addr2: "mongodb://10.206.206.4:27018"
mongodb_username: "admin"
mongodb_password: "password"

# KVRocks configuration
kvrocks_addr: "10.206.206.3:6666"
kvrocks_password: "password"

# CouchDB configuration
couchdb_addr: "http://10.206.206.4:5984"
couchdb_username: "admin"
couchdb_password: "password"

# Other databases configuration
cassandra_addr: ["10.206.206.4"]
dynamodb_addr: "http://localhost:8000"
tikv_addr: ["172.24.58.116:2379"]
