# Benchmark system configuration
executor_address_list: ["172.24.58.116:8001","172.24.58.115:8001"]
time_oracle_url: "http://172.24.58.116:8010"
zipfian_constant: 0.9
latency_value: 10

# Redis configuration
redis_addr: "172.24.58.116:6379"
redis_password: "password"

# MongoDB configuration
mongodb_addr1: "mongodb://172.24.58.116:27017"
mongodb_addr2: "mongodb://172.24.58.115:27018"
mongodb_username: "admin"
mongodb_password: "password"

# KVRocks configuration
kvrocks_addr: "172.24.58.116:6666"
kvrocks_password: "password"

# CouchDB configuration
couchdb_addr: "http://localhost:5984"
couchdb_username: "admin"
couchdb_password: "password"

# Other databases configuration
cassandra_addr: ["172.24.58.115"]
dynamodb_addr: "http://localhost:8000"
tikv_addr: ["localhost:2379"]